repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: check-added-large-files
            -   id: check-case-conflict
            #            -   id: check-executables-have-shebangs
            -   id: check-json
            -   id: pretty-format-json
                args: [ "--autofix" ]
            -   id: check-merge-conflict
            -   id: name-tests-test
            -   id: check-docstring-first
            -   id: requirements-txt-fixer

    -   repo: https://github.com/pycqa/isort
        rev: 5.6.4
        hooks:
            -   id: isort
                args: [ "--profile", "black", "--filter-files" ]

    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
            -   id: black
                language_version: python3
